### ISSUE TITLE
The last version 2.0.3 doesn't include any code

### ISSUE THREAD

**Issue by finnp** [cassels/dotpref#294]
I installed `dotpref@2.0.3` and it just has a `package.json` no code in it.

**Comment by cassels** [comment]
Hey @finnp, that's not very good 🤦  sorry about that and thanks for letting me know so promptly. My hunch is that after updating the GitHub actions for uploading (#291) and downloading (#290) artefacts during the build step something's broke and we're not retrieving the files correctly before publishing. I'll look into it now and mark `v2.0.3` as deprecated on NPM. 

Will keep you updated, thanks again,

**Comment by cassels** [comment]
Hey @finnp, thanks again for pointing this out; apologies for any inconvenience caused. Below is a quick summary of what occurred for posterity but the TL;DR is: deprecated `2.0.3`; fixed the problem; released `2.0.4`; and put a check in place to make sure an empty package isn't released again. I appreciate your patience and your support of the package 🚀 

### Summary
@renovate-bot is set up to merge minor & patch dependencies & devDependencies automatically; releases are only created for dependencies, not for devDependencies; for major changes, a PR is created to allow me to review the breaking change first.

Due to the fact that dotpref only has three dependencies and there's been no features or fixes, there's not been a release in 9 months; however, during that time there were two breaking changes to [github's download-artifact action](https://github.com/actions/download-artifact) which is used during the release pipeline. The breaking change from [v2 to v3](https://github.com/cassels/dotpref/pull/290) was assessed and accepted as a non issue, but the breaking change from [v1 to v2](https://github.com/cassels/dotpref/pull/220) was never reported in their release notes and therefore never highlighted by @renovate-bot and completely missed; however, in their readme I have now discovered [this backwards incompatibility](https://github.com/actions/download-artifact#compatibility-between-v1-and-v2v3).

### Actions Taken
- [x] Deprecate `dotpref@2.0.3` on NPM
- [x] [Follow the migration path for v1 to v3](https://github.com/cassels/dotpref/pull/300/files)
- [x] [Add pre-release check to ensure main files exist](https://github.com/cassels/dotpref/pull/298/files)
- [x] Release `dotpref@2.0.4` on NPM

**Comment by finnp** [comment]
Thank you for taking care of it 👍  Honestly I think npm should just not accept packages that do not include the file specified in the `main` field of the `package.json`
